networks:
  your-stream-net:
    driver: bridge

services:
  # Endpoints 
  rtmp:
    image: tiangolo/nginx-rtmp
    restart: unless-stopped
    ports:
      - "1935:1935"
    volumes:
      - ./StreamServer/nginx/rtmp.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - stream-api
    networks:
      - your-stream-net

  hls-server:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./StreamServer/nginx/hls.conf:/etc/nginx/nginx.conf:ro
      - /tmp/hls:/tmp/hls
    depends_on:
      - stream-api
    networks:
      - your-stream-net

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - rtmp
      - hls-server
      - main-api
      - frontend
      - chat-service
    networks:
      - your-stream-net

  mongo:
    image: 'mongo:latest'
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    networks:
      - your-stream-net
  
  redis:
    image: 'redis:latest'
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - your-stream-net

  # Stream processing services
  stream-api:
    build: ./StreamServer/stream-api
    restart: unless-stopped
    environment:
      - PORT=3000
      - AUTH_SERVICE_ADDRESS=http://service-manager-backend:3080
      - TRANSCODER_SERVICE_ADDRESS=http://transcoder:80
      - USER_AUTH_SERVICE_ADDRESS=http://auth-service:3000
      - SEARCH_SERVICE_ADDRESS=http://search-service:3000
      - MONGO_HOST=mongo
      - LOG_LEVEL=trace
    depends_on:
      - transcoder
      - service-manager-backend
      - auth-service
      - mongo
    networks:
      - your-stream-net
  transcoder:
    build: ./StreamServer/transcoder
    restart: unless-stopped
    environment:
      - PORT=80
      - AUTH_SERVICE_ADDRESS=http://service-manager-backend:3080
      - STREAM_API_HOST=http://stream-api:3000
      - ORIGINAL_RTMP_SERVER=rtmp:1935
      - LOG_LEVEL=trace
    depends_on:
      - service-manager-backend
    volumes:
      - /tmp/hls:/tmp/hls
    networks:
      - your-stream-net
  viewer-api:
    build: ./StreamServer/viewer-api
    restart: unless-stopped
    environment:
      - PORT=3000
      - STREAM_API_HOST=http://stream-api:3000
      - TRANSCODER_SERVICE_ADDRESS=http://transcoder:3000
      - AUTH_SERVICE_ADDRESS=http://service-manager-backend:3080
      - LOG_LEVEL=trace
    networks:
      - your-stream-net

  # Service Manager
  service-manager-backend:
    build: ./Services/ServiceManager/backend
    restart: unless-stopped
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=
      - MONGO_PASSWORD=
      - MONGO_DB=YourStream-ServiceManager
      - PORT=3080
    depends_on:
      - mongo
    networks:
      - your-stream-net
  service-manager-frontend:
    build: ./Services/ServiceManager/service-manager-admin
    restart: unless-stopped
    ports:
      - '8019:80'
    depends_on:
      - service-manager-backend
    networks:
      - your-stream-net

  # Authentication Service
  auth-service:
    build: ./Services/AuthService
    restart: unless-stopped
    environment:
      - AUTH_SERVICE_ADDRESS=http://service-manager-backend:3080
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=
      - MONGO_PASSWORD=
      - MONGO_DB=YourStream-Auth
      - PORT=3000
      - LOG_LEVEL=trace
    depends_on:
      - mongo
      - service-manager-backend
    networks:
      - your-stream-net
  
  # Chat Service
  chat-service:
    build: ./Services/ChatService
    restart: unless-stopped
    environment:
      - AUTH_SERVICE_ADDRESS=http://service-manager-backend:3080
      - USER_AUTH_SERVICE_ADDRESS=http://auth-service:3000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=
      - MONGO_PASSWORD=
      - MONGO_DB=YourStream-Chat
      - REDIS_HOST=redis:6379
      - PORT=3000
      - LOG_LEVEL=trace
    depends_on:
      - mongo
      - service-manager-backend
    networks:
      - your-stream-net

  # Search Service
  search-service:
    build: ./Services/SearchService
    restart: unless-stopped
    environment:
      - AUTH_SERVICE_ADDRESS=http://service-manager-backend:3080
      - STREAM_API_SERVICE_ADDRESS=http://stream-api:3000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=
      - MONGO_PASSWORD=
      - MONGO_DB=YourStream-Search
      - REDIS_HOST=redis:6379
      - PORT=3000
      - LOG_LEVEL=trace
    depends_on:
      - mongo
      - service-manager-backend
      - auth-service
    networks:
      - your-stream-net

  # Monolithic Server :/
  main-api:
    build: ./Server.API
    restart: unless-stopped
    environment:
      - AUTH_SERVICE_ADDRESS=http://service-manager-backend:3080
      - USER_AUTH_SERVICE_ADDRESS=http://auth-service:3000
      - STREAM_API_SERVICE_ADDRESS=http://stream-api:3000
      - CHAT_SERVICE_ADDRESS=http://chat-service:3000
      - PORT=3000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=
      - MONGO_PASSWORD=
      - MONGO_DB=YourStream-Main
      - REDIS_HOST=redis:6379
    depends_on:
      - mongo
      - redis
      - service-manager-backend
      - auth-service
      - chat-service
      - stream-api
      - search-service
    networks:
      - your-stream-net

  # Frontend
  frontend:
    build: ./YourStreamWebApp
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - PUBLIC_BACKEND_URL="123"
    depends_on:
      - chat-service
      - main-api
    networks:
      - your-stream-net