services:
  rtmp:
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935"
    volumes:
      - ./StreamServer/nginx/rtmp.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - stream-api
    networks:
      - your-stream-net

  hls-server:
    image: nginx:latest
    volumes:
      - ./StreamServer/nginx/hls.conf:/etc/nginx/nginx.conf:ro
      - /tmp/hls:/tmp/hls
    depends_on:
      - stream-api
    networks:
      - your-stream-net

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - rtmp
      - hls-server
    networks:
      - your-stream-net

  # web-app:
  #   build: ./YourStreamWebApp
  #   networks:
  #     - your-stream-net

  mongo:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    networks:
      - your-stream-net
  
  stream-api:
    build: ./StreamServer/stream-api
    environment:
      - PORT=3000
      - AUTH_SERVICE_ADDRESS=http://service-manager-backend:3080
      - TRANSCODER_SERVICE_ADDRESS=http://transcoder:80
      - MONGO_HOST=mongo
      - LOG_LEVEL=trace
    depends_on:
      - transcoder
      - service-manager-backend
    networks:
      - your-stream-net


  transcoder:
    build: ./StreamServer/transcoder
    environment:
      - PORT=80
      - AUTH_SERVICE_ADDRESS=http://service-manager-backend:3080
      - STREAM_API_HOST=stream-api:3000
      - ORIGINAL_RTMP_SERVER=rtmp:1935
      - LOG_LEVEL=trace
    depends_on:
      - service-manager-backend
    volumes:
      - /tmp/hls:/tmp/hls
    networks:
      - your-stream-net

  viewer-api:
    build: ./StreamServer/viewer-api
    environment:
      - PORT=3000
      - STREAM_API_HOST=http://stream-api:3000
      - TRANSCODER_SERVICE_ADDRESS=http://transcoder:3000
      - AUTH_SERVICE_ADDRESS=http://service-manager-backend:3080
      - LOG_LEVEL=trace
    networks:
      - your-stream-net

  service-manager-backend:
    build: ./Services/ServiceManager/backend
    restart: unless-stopped
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=
      - MONGO_PASSWORD=
      - MONGO_DB=YourStream-ServiceManager
      - PORT=3080
    depends_on:
      - mongo
    networks:
      - your-stream-net

  service-manager-frontend:
    build: ./Services/ServiceManager/service-manager-admin
    restart: unless-stopped
    ports:
      - '8019:80'
    depends_on:
      - service-manager-backend
    networks:
      - your-stream-net

networks:
  your-stream-net:
    driver: bridge
