services:
  nginx-rtmp:
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935"
    volumes:
      - ./StreamServer/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /tmp/hls:/tmp/hls
    depends_on:
      - stream-api
    networks:
      - your-stream-net

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nginx-rtmp
    networks:
      - your-stream-net

  mongo:
    image: 'mongo:latest'
    ports:
      - '27010:27017'
    volumes:
      - ./data:/data/db
    networks:
      - your-stream-net
  
  stream-api:
    build: ./StreamServer/stream-api
    environment:
      - PORT=3000
      - AUTH_SERVICE_ADDRESS=http://service-manager-backend:3080
      - TRANSCODER_SERVICE_ADDRESS=http://transcoder:3000
      - MONGO_HOST=mongo
    depends_on:
      - transcoder
    networks:
      - your-stream-net

  transcoder:
    build: ./StreamServer/transcoder
    environment:
      - PORT=3000
      - AUTH_SERVICE_ADDRESS=http://service-manager-backend:3080
      - STREAM_API_HOST=stream-api:3000
      - RTMP_SERVER=nginx-rtmp:1935
    networks:
      - your-stream-net
  
  viewer-api:
    build: ./StreamServer/viewer-api
    environment:
      - PORT=3000
      - STREAM_API_HOST=stream-api:3000
    networks:
      - your-stream-net

  service-manager-backend:
    build: ./Services/ServiceManager/backend
    restart: unless-stopped
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=
      - MONGO_PASSWORD=
      - MONGO_DB=YourStream-ServiceManager
      - PORT=3080
    depends_on:
      - mongo
    networks:
      - your-stream-net

  service-manager-frontend:
    build: ./Services/ServiceManager/service-manager-admin
    restart: unless-stopped
    ports:
      - '8019:80'
    depends_on:
      - service-manager-backend
    networks:
      - your-stream-net

networks:
  your-stream-net:
    driver: bridge
